//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.27 at 06:08:42 PM PDT 
//


package ebay.apis.eblbasecomponents;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 					A report that contains all of the active listings for a specific seller. The eBay
 * 					servers read the token information passed in by the seller's application to
 * 					determine which seller's data to retrieve.
 * 				
 * 
 * <p>Java class for ActiveInventoryReportResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActiveInventoryReportResponseType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:ebay:apis:eBLBaseComponents}AbstractResponseType">
 *       &lt;sequence>
 *         &lt;element name="SKUDetails" type="{urn:ebay:apis:eBLBaseComponents}SKUDetailsType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActiveInventoryReportResponseType", propOrder = {
    "skuDetails"
})
public class ActiveInventoryReportResponseType
    extends AbstractResponseType
{

    @XmlElement(name = "SKUDetails")
    protected List<SKUDetailsType> skuDetails;

    /**
     * Gets the value of the skuDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the skuDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSKUDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SKUDetailsType }
     * 
     * 
     */
    public List<SKUDetailsType> getSKUDetails() {
        if (skuDetails == null) {
            skuDetails = new ArrayList<SKUDetailsType>();
        }
        return this.skuDetails;
    }

}
