//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.27 at 06:08:42 PM PDT 
//


package ebay.apis.eblbasecomponents;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Container for Bulk Data Exchange Requests.
 * 			
 * 
 * <p>Java class for BulkDataExchangeRequestsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BulkDataExchangeRequestsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{urn:ebay:apis:eBLBaseComponents}MerchantDataRequestHeaderType" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="AddFixedPriceItemRequest" type="{urn:ebay:apis:eBLBaseComponents}AddFixedPriceItemRequestType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="AddItemRequest" type="{urn:ebay:apis:eBLBaseComponents}AddItemRequestType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="EndFixedPriceItemRequest" type="{urn:ebay:apis:eBLBaseComponents}EndFixedPriceItemRequestType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="EndItemRequest" type="{urn:ebay:apis:eBLBaseComponents}EndItemRequestType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="OrderAckRequest" type="{urn:ebay:apis:eBLBaseComponents}OrderAckRequestType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="RelistFixedPriceItemRequest" type="{urn:ebay:apis:eBLBaseComponents}RelistFixedPriceItemRequestType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="RelistItemRequest" type="{urn:ebay:apis:eBLBaseComponents}RelistItemRequestType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="ReviseFixedPriceItemRequest" type="{urn:ebay:apis:eBLBaseComponents}ReviseFixedPriceItemRequestType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="ReviseInventoryStatusRequest" type="{urn:ebay:apis:eBLBaseComponents}ReviseInventoryStatusRequestType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="ReviseItemRequest" type="{urn:ebay:apis:eBLBaseComponents}ReviseItemRequestType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="SetShipmentTrackingInfoRequest" type="{urn:ebay:apis:eBLBaseComponents}SetShipmentTrackingInfoRequestType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="UploadSiteHostedPicturesRequest" type="{urn:ebay:apis:eBLBaseComponents}UploadSiteHostedPicturesRequestType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="VerifyAddFixedPriceItemRequest" type="{urn:ebay:apis:eBLBaseComponents}VerifyAddFixedPriceItemRequestType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="VerifyAddItemRequest" type="{urn:ebay:apis:eBLBaseComponents}VerifyAddItemRequestType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BulkDataExchangeRequestsType", propOrder = {
    "header",
    "addFixedPriceItemRequest",
    "addItemRequest",
    "endFixedPriceItemRequest",
    "endItemRequest",
    "orderAckRequest",
    "relistFixedPriceItemRequest",
    "relistItemRequest",
    "reviseFixedPriceItemRequest",
    "reviseInventoryStatusRequest",
    "reviseItemRequest",
    "setShipmentTrackingInfoRequest",
    "uploadSiteHostedPicturesRequest",
    "verifyAddFixedPriceItemRequest",
    "verifyAddItemRequest"
})
public class BulkDataExchangeRequestsType {

    @XmlElement(name = "Header")
    protected MerchantDataRequestHeaderType header;
    @XmlElement(name = "AddFixedPriceItemRequest")
    protected List<AddFixedPriceItemRequestType> addFixedPriceItemRequest;
    @XmlElement(name = "AddItemRequest")
    protected List<AddItemRequestType> addItemRequest;
    @XmlElement(name = "EndFixedPriceItemRequest")
    protected List<EndFixedPriceItemRequestType> endFixedPriceItemRequest;
    @XmlElement(name = "EndItemRequest")
    protected List<EndItemRequestType> endItemRequest;
    @XmlElement(name = "OrderAckRequest")
    protected List<OrderAckRequestType> orderAckRequest;
    @XmlElement(name = "RelistFixedPriceItemRequest")
    protected List<RelistFixedPriceItemRequestType> relistFixedPriceItemRequest;
    @XmlElement(name = "RelistItemRequest")
    protected List<RelistItemRequestType> relistItemRequest;
    @XmlElement(name = "ReviseFixedPriceItemRequest")
    protected List<ReviseFixedPriceItemRequestType> reviseFixedPriceItemRequest;
    @XmlElement(name = "ReviseInventoryStatusRequest")
    protected List<ReviseInventoryStatusRequestType> reviseInventoryStatusRequest;
    @XmlElement(name = "ReviseItemRequest")
    protected List<ReviseItemRequestType> reviseItemRequest;
    @XmlElement(name = "SetShipmentTrackingInfoRequest")
    protected List<SetShipmentTrackingInfoRequestType> setShipmentTrackingInfoRequest;
    @XmlElement(name = "UploadSiteHostedPicturesRequest")
    protected List<UploadSiteHostedPicturesRequestType> uploadSiteHostedPicturesRequest;
    @XmlElement(name = "VerifyAddFixedPriceItemRequest")
    protected List<VerifyAddFixedPriceItemRequestType> verifyAddFixedPriceItemRequest;
    @XmlElement(name = "VerifyAddItemRequest")
    protected List<VerifyAddItemRequestType> verifyAddItemRequest;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link MerchantDataRequestHeaderType }
     *     
     */
    public MerchantDataRequestHeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link MerchantDataRequestHeaderType }
     *     
     */
    public void setHeader(MerchantDataRequestHeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the addFixedPriceItemRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addFixedPriceItemRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddFixedPriceItemRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddFixedPriceItemRequestType }
     * 
     * 
     */
    public List<AddFixedPriceItemRequestType> getAddFixedPriceItemRequest() {
        if (addFixedPriceItemRequest == null) {
            addFixedPriceItemRequest = new ArrayList<AddFixedPriceItemRequestType>();
        }
        return this.addFixedPriceItemRequest;
    }

    /**
     * Gets the value of the addItemRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addItemRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddItemRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddItemRequestType }
     * 
     * 
     */
    public List<AddItemRequestType> getAddItemRequest() {
        if (addItemRequest == null) {
            addItemRequest = new ArrayList<AddItemRequestType>();
        }
        return this.addItemRequest;
    }

    /**
     * Gets the value of the endFixedPriceItemRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the endFixedPriceItemRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEndFixedPriceItemRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EndFixedPriceItemRequestType }
     * 
     * 
     */
    public List<EndFixedPriceItemRequestType> getEndFixedPriceItemRequest() {
        if (endFixedPriceItemRequest == null) {
            endFixedPriceItemRequest = new ArrayList<EndFixedPriceItemRequestType>();
        }
        return this.endFixedPriceItemRequest;
    }

    /**
     * Gets the value of the endItemRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the endItemRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEndItemRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EndItemRequestType }
     * 
     * 
     */
    public List<EndItemRequestType> getEndItemRequest() {
        if (endItemRequest == null) {
            endItemRequest = new ArrayList<EndItemRequestType>();
        }
        return this.endItemRequest;
    }

    /**
     * Gets the value of the orderAckRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderAckRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderAckRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderAckRequestType }
     * 
     * 
     */
    public List<OrderAckRequestType> getOrderAckRequest() {
        if (orderAckRequest == null) {
            orderAckRequest = new ArrayList<OrderAckRequestType>();
        }
        return this.orderAckRequest;
    }

    /**
     * Gets the value of the relistFixedPriceItemRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relistFixedPriceItemRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelistFixedPriceItemRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelistFixedPriceItemRequestType }
     * 
     * 
     */
    public List<RelistFixedPriceItemRequestType> getRelistFixedPriceItemRequest() {
        if (relistFixedPriceItemRequest == null) {
            relistFixedPriceItemRequest = new ArrayList<RelistFixedPriceItemRequestType>();
        }
        return this.relistFixedPriceItemRequest;
    }

    /**
     * Gets the value of the relistItemRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relistItemRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelistItemRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelistItemRequestType }
     * 
     * 
     */
    public List<RelistItemRequestType> getRelistItemRequest() {
        if (relistItemRequest == null) {
            relistItemRequest = new ArrayList<RelistItemRequestType>();
        }
        return this.relistItemRequest;
    }

    /**
     * Gets the value of the reviseFixedPriceItemRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reviseFixedPriceItemRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReviseFixedPriceItemRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReviseFixedPriceItemRequestType }
     * 
     * 
     */
    public List<ReviseFixedPriceItemRequestType> getReviseFixedPriceItemRequest() {
        if (reviseFixedPriceItemRequest == null) {
            reviseFixedPriceItemRequest = new ArrayList<ReviseFixedPriceItemRequestType>();
        }
        return this.reviseFixedPriceItemRequest;
    }

    /**
     * Gets the value of the reviseInventoryStatusRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reviseInventoryStatusRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReviseInventoryStatusRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReviseInventoryStatusRequestType }
     * 
     * 
     */
    public List<ReviseInventoryStatusRequestType> getReviseInventoryStatusRequest() {
        if (reviseInventoryStatusRequest == null) {
            reviseInventoryStatusRequest = new ArrayList<ReviseInventoryStatusRequestType>();
        }
        return this.reviseInventoryStatusRequest;
    }

    /**
     * Gets the value of the reviseItemRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reviseItemRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReviseItemRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReviseItemRequestType }
     * 
     * 
     */
    public List<ReviseItemRequestType> getReviseItemRequest() {
        if (reviseItemRequest == null) {
            reviseItemRequest = new ArrayList<ReviseItemRequestType>();
        }
        return this.reviseItemRequest;
    }

    /**
     * Gets the value of the setShipmentTrackingInfoRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the setShipmentTrackingInfoRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSetShipmentTrackingInfoRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SetShipmentTrackingInfoRequestType }
     * 
     * 
     */
    public List<SetShipmentTrackingInfoRequestType> getSetShipmentTrackingInfoRequest() {
        if (setShipmentTrackingInfoRequest == null) {
            setShipmentTrackingInfoRequest = new ArrayList<SetShipmentTrackingInfoRequestType>();
        }
        return this.setShipmentTrackingInfoRequest;
    }

    /**
     * Gets the value of the uploadSiteHostedPicturesRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the uploadSiteHostedPicturesRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUploadSiteHostedPicturesRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UploadSiteHostedPicturesRequestType }
     * 
     * 
     */
    public List<UploadSiteHostedPicturesRequestType> getUploadSiteHostedPicturesRequest() {
        if (uploadSiteHostedPicturesRequest == null) {
            uploadSiteHostedPicturesRequest = new ArrayList<UploadSiteHostedPicturesRequestType>();
        }
        return this.uploadSiteHostedPicturesRequest;
    }

    /**
     * Gets the value of the verifyAddFixedPriceItemRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the verifyAddFixedPriceItemRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVerifyAddFixedPriceItemRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VerifyAddFixedPriceItemRequestType }
     * 
     * 
     */
    public List<VerifyAddFixedPriceItemRequestType> getVerifyAddFixedPriceItemRequest() {
        if (verifyAddFixedPriceItemRequest == null) {
            verifyAddFixedPriceItemRequest = new ArrayList<VerifyAddFixedPriceItemRequestType>();
        }
        return this.verifyAddFixedPriceItemRequest;
    }

    /**
     * Gets the value of the verifyAddItemRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the verifyAddItemRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVerifyAddItemRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VerifyAddItemRequestType }
     * 
     * 
     */
    public List<VerifyAddItemRequestType> getVerifyAddItemRequest() {
        if (verifyAddItemRequest == null) {
            verifyAddItemRequest = new ArrayList<VerifyAddItemRequestType>();
        }
        return this.verifyAddItemRequest;
    }

}
