//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.27 at 06:08:42 PM PDT 
//


package ebay.apis.eblbasecomponents;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BusinessRoleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BusinessRoleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Shopper"/>
 *     &lt;enumeration value="FullMarketPlaceParticipant"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BusinessRoleType")
@XmlEnum
public enum BusinessRoleType {


    /**
     * 
     * 						This value indicates that the eBay user's account is a Partially Provisioned Account
     * 						without buying and selling privileges on eBay.
     * 					
     * 
     */
    @XmlEnumValue("Shopper")
    SHOPPER("Shopper"),

    /**
     * 
     * 						This value indicates that the eBay user's account is a fully provisioned account with buying
     * 						and selling privileges on eBay.
     * 					
     * 
     */
    @XmlEnumValue("FullMarketPlaceParticipant")
    FULL_MARKET_PLACE_PARTICIPANT("FullMarketPlaceParticipant");
    private final String value;

    BusinessRoleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BusinessRoleType fromValue(String v) {
        for (BusinessRoleType c: BusinessRoleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
