//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.27 at 06:08:42 PM PDT 
//


package ebay.apis.eblbasecomponents;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 * 				The information of nonprofit charity organization affiliation.
 * 			
 * 
 * <p>Java class for CharityAffiliationDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CharityAffiliationDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CharityID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AffiliationType" type="{urn:ebay:apis:eBLBaseComponents}CharityAffiliationTypeCodeType" minOccurs="0"/>
 *         &lt;element name="LastUsedTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CharityAffiliationDetailType", propOrder = {
    "charityID",
    "affiliationType",
    "lastUsedTime"
})
public class CharityAffiliationDetailType {

    @XmlElement(name = "CharityID")
    protected String charityID;
    @XmlElement(name = "AffiliationType")
    protected CharityAffiliationTypeCodeType affiliationType;
    @XmlElement(name = "LastUsedTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastUsedTime;

    /**
     * Gets the value of the charityID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCharityID() {
        return charityID;
    }

    /**
     * Sets the value of the charityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCharityID(String value) {
        this.charityID = value;
    }

    /**
     * Gets the value of the affiliationType property.
     * 
     * @return
     *     possible object is
     *     {@link CharityAffiliationTypeCodeType }
     *     
     */
    public CharityAffiliationTypeCodeType getAffiliationType() {
        return affiliationType;
    }

    /**
     * Sets the value of the affiliationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CharityAffiliationTypeCodeType }
     *     
     */
    public void setAffiliationType(CharityAffiliationTypeCodeType value) {
        this.affiliationType = value;
    }

    /**
     * Gets the value of the lastUsedTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastUsedTime() {
        return lastUsedTime;
    }

    /**
     * Sets the value of the lastUsedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastUsedTime(XMLGregorianCalendar value) {
        this.lastUsedTime = value;
    }

}
