//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.27 at 06:08:42 PM PDT 
//


package ebay.apis.eblbasecomponents;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 * 				Contains information about user invoice and related order information, such as: fee type, fee amount, item category, order id,
 * 				transaction id, item id, and item title. Some setup steps are required. See the Knowledgebase Article at the following link.
 * 			
 * 
 * <p>Java class for FeeSettlementReportResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FeeSettlementReportResponseType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:ebay:apis:eBLBaseComponents}AbstractResponseType">
 *       &lt;sequence>
 *         &lt;element name="InvoiceID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SellerID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AccountID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReportStartTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="ReportEndTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="InvoiceProcessingTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="ReportProcessingTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="FeeSettlementAmount" type="{urn:ebay:apis:eBLBaseComponents}AmountType" minOccurs="0"/>
 *         &lt;element name="LastInvoiceAmount" type="{urn:ebay:apis:eBLBaseComponents}AmountType" minOccurs="0"/>
 *         &lt;element name="FeeRoundingAdjustmentAmount" type="{urn:ebay:apis:eBLBaseComponents}AmountType" minOccurs="0"/>
 *         &lt;element name="FeeTotalUsageAdjustmentAmount" type="{urn:ebay:apis:eBLBaseComponents}AmountType" minOccurs="0"/>
 *         &lt;element name="OrderTransactionList" type="{urn:ebay:apis:eBLBaseComponents}OrderDetailsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ListingTransactionList" type="{urn:ebay:apis:eBLBaseComponents}TransactionListType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OrderAdjustmentList" type="{urn:ebay:apis:eBLBaseComponents}OrderDetailsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AccountTransactionList" type="{urn:ebay:apis:eBLBaseComponents}AccountTransactionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DiscountTransactionList" type="{urn:ebay:apis:eBLBaseComponents}AccountTransactionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FeeSettlementReportResponseType", propOrder = {
    "invoiceID",
    "sellerID",
    "accountID",
    "reportStartTime",
    "reportEndTime",
    "invoiceProcessingTime",
    "reportProcessingTime",
    "feeSettlementAmount",
    "lastInvoiceAmount",
    "feeRoundingAdjustmentAmount",
    "feeTotalUsageAdjustmentAmount",
    "orderTransactionList",
    "listingTransactionList",
    "orderAdjustmentList",
    "accountTransactionList",
    "discountTransactionList"
})
public class FeeSettlementReportResponseType
    extends AbstractResponseType
{

    @XmlElement(name = "InvoiceID")
    protected String invoiceID;
    @XmlElement(name = "SellerID")
    protected String sellerID;
    @XmlElement(name = "AccountID")
    protected String accountID;
    @XmlElement(name = "ReportStartTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar reportStartTime;
    @XmlElement(name = "ReportEndTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar reportEndTime;
    @XmlElement(name = "InvoiceProcessingTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar invoiceProcessingTime;
    @XmlElement(name = "ReportProcessingTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar reportProcessingTime;
    @XmlElement(name = "FeeSettlementAmount")
    protected AmountType feeSettlementAmount;
    @XmlElement(name = "LastInvoiceAmount")
    protected AmountType lastInvoiceAmount;
    @XmlElement(name = "FeeRoundingAdjustmentAmount")
    protected AmountType feeRoundingAdjustmentAmount;
    @XmlElement(name = "FeeTotalUsageAdjustmentAmount")
    protected AmountType feeTotalUsageAdjustmentAmount;
    @XmlElement(name = "OrderTransactionList")
    protected List<OrderDetailsType> orderTransactionList;
    @XmlElement(name = "ListingTransactionList")
    protected List<TransactionListType> listingTransactionList;
    @XmlElement(name = "OrderAdjustmentList")
    protected List<OrderDetailsType> orderAdjustmentList;
    @XmlElement(name = "AccountTransactionList")
    protected List<AccountTransactionType> accountTransactionList;
    @XmlElement(name = "DiscountTransactionList")
    protected List<AccountTransactionType> discountTransactionList;

    /**
     * Gets the value of the invoiceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceID() {
        return invoiceID;
    }

    /**
     * Sets the value of the invoiceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceID(String value) {
        this.invoiceID = value;
    }

    /**
     * Gets the value of the sellerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellerID() {
        return sellerID;
    }

    /**
     * Sets the value of the sellerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSellerID(String value) {
        this.sellerID = value;
    }

    /**
     * Gets the value of the accountID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountID() {
        return accountID;
    }

    /**
     * Sets the value of the accountID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountID(String value) {
        this.accountID = value;
    }

    /**
     * Gets the value of the reportStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReportStartTime() {
        return reportStartTime;
    }

    /**
     * Sets the value of the reportStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReportStartTime(XMLGregorianCalendar value) {
        this.reportStartTime = value;
    }

    /**
     * Gets the value of the reportEndTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReportEndTime() {
        return reportEndTime;
    }

    /**
     * Sets the value of the reportEndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReportEndTime(XMLGregorianCalendar value) {
        this.reportEndTime = value;
    }

    /**
     * Gets the value of the invoiceProcessingTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInvoiceProcessingTime() {
        return invoiceProcessingTime;
    }

    /**
     * Sets the value of the invoiceProcessingTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInvoiceProcessingTime(XMLGregorianCalendar value) {
        this.invoiceProcessingTime = value;
    }

    /**
     * Gets the value of the reportProcessingTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReportProcessingTime() {
        return reportProcessingTime;
    }

    /**
     * Sets the value of the reportProcessingTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReportProcessingTime(XMLGregorianCalendar value) {
        this.reportProcessingTime = value;
    }

    /**
     * Gets the value of the feeSettlementAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getFeeSettlementAmount() {
        return feeSettlementAmount;
    }

    /**
     * Sets the value of the feeSettlementAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setFeeSettlementAmount(AmountType value) {
        this.feeSettlementAmount = value;
    }

    /**
     * Gets the value of the lastInvoiceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getLastInvoiceAmount() {
        return lastInvoiceAmount;
    }

    /**
     * Sets the value of the lastInvoiceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setLastInvoiceAmount(AmountType value) {
        this.lastInvoiceAmount = value;
    }

    /**
     * Gets the value of the feeRoundingAdjustmentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getFeeRoundingAdjustmentAmount() {
        return feeRoundingAdjustmentAmount;
    }

    /**
     * Sets the value of the feeRoundingAdjustmentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setFeeRoundingAdjustmentAmount(AmountType value) {
        this.feeRoundingAdjustmentAmount = value;
    }

    /**
     * Gets the value of the feeTotalUsageAdjustmentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getFeeTotalUsageAdjustmentAmount() {
        return feeTotalUsageAdjustmentAmount;
    }

    /**
     * Sets the value of the feeTotalUsageAdjustmentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setFeeTotalUsageAdjustmentAmount(AmountType value) {
        this.feeTotalUsageAdjustmentAmount = value;
    }

    /**
     * Gets the value of the orderTransactionList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderTransactionList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderTransactionList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderDetailsType }
     * 
     * 
     */
    public List<OrderDetailsType> getOrderTransactionList() {
        if (orderTransactionList == null) {
            orderTransactionList = new ArrayList<OrderDetailsType>();
        }
        return this.orderTransactionList;
    }

    /**
     * Gets the value of the listingTransactionList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the listingTransactionList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getListingTransactionList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransactionListType }
     * 
     * 
     */
    public List<TransactionListType> getListingTransactionList() {
        if (listingTransactionList == null) {
            listingTransactionList = new ArrayList<TransactionListType>();
        }
        return this.listingTransactionList;
    }

    /**
     * Gets the value of the orderAdjustmentList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderAdjustmentList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderAdjustmentList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderDetailsType }
     * 
     * 
     */
    public List<OrderDetailsType> getOrderAdjustmentList() {
        if (orderAdjustmentList == null) {
            orderAdjustmentList = new ArrayList<OrderDetailsType>();
        }
        return this.orderAdjustmentList;
    }

    /**
     * Gets the value of the accountTransactionList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accountTransactionList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccountTransactionList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccountTransactionType }
     * 
     * 
     */
    public List<AccountTransactionType> getAccountTransactionList() {
        if (accountTransactionList == null) {
            accountTransactionList = new ArrayList<AccountTransactionType>();
        }
        return this.accountTransactionList;
    }

    /**
     * Gets the value of the discountTransactionList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the discountTransactionList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiscountTransactionList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccountTransactionType }
     * 
     * 
     */
    public List<AccountTransactionType> getDiscountTransactionList() {
        if (discountTransactionList == null) {
            discountTransactionList = new ArrayList<AccountTransactionType>();
        }
        return this.discountTransactionList;
    }

}
