//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.27 at 06:08:42 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:ebay:apis:eBLBaseComponents", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ebay.apis.eblbasecomponents;
