
package com.ebay.marketplace.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.5-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "FileTransferServicePort", targetNamespace = "http://www.ebay.com/marketplace/services")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FileTransferServicePort {


    /**
     * 
     * @param params
     * @return
     *     returns com.ebay.marketplace.services.UploadFileResponse
     */
    @WebMethod(action = "urn:uploadFile")
    @WebResult(name = "uploadFileResponse", targetNamespace = "http://www.ebay.com/marketplace/services", partName = "params")
    public UploadFileResponse uploadFile(
        @WebParam(name = "uploadFileRequest", targetNamespace = "http://www.ebay.com/marketplace/services", partName = "params")
        UploadFileRequest params);

    /**
     * 
     * @param params
     * @return
     *     returns com.ebay.marketplace.services.DownloadFileResponse
     */
    @WebMethod(action = "urn:downloadFile")
    @WebResult(name = "downloadFileResponse", targetNamespace = "http://www.ebay.com/marketplace/services", partName = "params")
    public DownloadFileResponse downloadFile(
        @WebParam(name = "downloadFileRequest", targetNamespace = "http://www.ebay.com/marketplace/services", partName = "params")
        DownloadFileRequest params);

}
