//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.27 at 04:06:26 PM PDT 
//


package ebay.apis.eblbasecomponents;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				A pairing of range and insurance cost.
 * 			
 * 
 * <p>Java class for FlatRateInsuranceRangeCostType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlatRateInsuranceRangeCostType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FlatRateInsuranceRange" type="{urn:ebay:apis:eBLBaseComponents}FlatRateInsuranceRangeCodeType" minOccurs="0"/>
 *         &lt;element name="InsuranceCost" type="{urn:ebay:apis:eBLBaseComponents}AmountType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlatRateInsuranceRangeCostType", propOrder = {
    "flatRateInsuranceRange",
    "insuranceCost"
})
public class FlatRateInsuranceRangeCostType {

    @XmlElement(name = "FlatRateInsuranceRange")
    protected FlatRateInsuranceRangeCodeType flatRateInsuranceRange;
    @XmlElement(name = "InsuranceCost")
    protected AmountType insuranceCost;

    /**
     * Gets the value of the flatRateInsuranceRange property.
     * 
     * @return
     *     possible object is
     *     {@link FlatRateInsuranceRangeCodeType }
     *     
     */
    public FlatRateInsuranceRangeCodeType getFlatRateInsuranceRange() {
        return flatRateInsuranceRange;
    }

    /**
     * Sets the value of the flatRateInsuranceRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlatRateInsuranceRangeCodeType }
     *     
     */
    public void setFlatRateInsuranceRange(FlatRateInsuranceRangeCodeType value) {
        this.flatRateInsuranceRange = value;
    }

    /**
     * Gets the value of the insuranceCost property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getInsuranceCost() {
        return insuranceCost;
    }

    /**
     * Sets the value of the insuranceCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setInsuranceCost(AmountType value) {
        this.insuranceCost = value;
    }

}
