//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.27 at 04:06:26 PM PDT 
//


package ebay.apis.eblbasecomponents;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Retrieves the Product Finder XSL stylesheet. Apply the stylesheet to the
 * 				XML returned from a call to GetProductFinder to
 * 				render a form that lets a user form a multi-attribute query against
 * 				eBay catalog data.
 * 				See the Developer's Guide for an overview of Pre-filled Item Information
 * 				and information on searching for catalog products.
 * 			
 * 
 * <p>Java class for GetProductFinderXSLResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetProductFinderXSLResponseType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:ebay:apis:eBLBaseComponents}AbstractResponseType">
 *       &lt;sequence>
 *         &lt;element name="XSLFile" type="{urn:ebay:apis:eBLBaseComponents}XSLFileType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetProductFinderXSLResponseType", propOrder = {
    "xslFile"
})
public class GetProductFinderXSLResponseType
    extends AbstractResponseType
{

    @XmlElement(name = "XSLFile")
    protected List<XSLFileType> xslFile;

    /**
     * Gets the value of the xslFile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the xslFile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getXSLFile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XSLFileType }
     * 
     * 
     */
    public List<XSLFileType> getXSLFile() {
        if (xslFile == null) {
            xslFile = new ArrayList<XSLFileType>();
        }
        return this.xslFile;
    }

}
