//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.27 at 04:06:26 PM PDT 
//


package ebay.apis.eblbasecomponents;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				GetProductFamilyMembers performs a product search and returns results comprising
 * 				all the children in the product family identified by a product ID that was
 * 				specified in the request. Use this call when more matches are found than the
 * 				max amount specified per family in a call to GetProductSearchResults.
 * 				This call supports batch requests. This means you can retrieve products in
 * 				multiple families by using a single request.
 * 				The results are compatible with the results from GetProductSearchResults,
 * 				so similar application logic can be used to handle both requests and responses.
 * 			
 * 
 * <p>Java class for GetProductFamilyMembersResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetProductFamilyMembersResponseType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:ebay:apis:eBLBaseComponents}AbstractResponseType">
 *       &lt;sequence>
 *         &lt;element name="DataElementSets" type="{urn:ebay:apis:eBLBaseComponents}DataElementSetType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ProductSearchResult" type="{urn:ebay:apis:eBLBaseComponents}ProductSearchResultType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetProductFamilyMembersResponseType", propOrder = {
    "dataElementSets",
    "productSearchResult"
})
public class GetProductFamilyMembersResponseType
    extends AbstractResponseType
{

    @XmlElement(name = "DataElementSets")
    protected List<DataElementSetType> dataElementSets;
    @XmlElement(name = "ProductSearchResult")
    protected List<ProductSearchResultType> productSearchResult;

    /**
     * Gets the value of the dataElementSets property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataElementSets property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataElementSets().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataElementSetType }
     * 
     * 
     */
    public List<DataElementSetType> getDataElementSets() {
        if (dataElementSets == null) {
            dataElementSets = new ArrayList<DataElementSetType>();
        }
        return this.dataElementSets;
    }

    /**
     * Gets the value of the productSearchResult property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productSearchResult property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductSearchResult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductSearchResultType }
     * 
     * 
     */
    public List<ProductSearchResultType> getProductSearchResult() {
        if (productSearchResult == null) {
            productSearchResult = new ArrayList<ProductSearchResultType>();
        }
        return this.productSearchResult;
    }

}
