//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.27 at 04:06:26 PM PDT 
//


package ebay.apis.eblbasecomponents;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Contains the custom page or pages for the user's Store.
 * 			
 * 
 * <p>Java class for GetStoreCustomPageResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetStoreCustomPageResponseType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:ebay:apis:eBLBaseComponents}AbstractResponseType">
 *       &lt;sequence>
 *         &lt;element name="CustomPageArray" type="{urn:ebay:apis:eBLBaseComponents}StoreCustomPageArrayType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetStoreCustomPageResponseType", propOrder = {
    "customPageArray"
})
public class GetStoreCustomPageResponseType
    extends AbstractResponseType
{

    @XmlElement(name = "CustomPageArray")
    protected StoreCustomPageArrayType customPageArray;

    /**
     * Gets the value of the customPageArray property.
     * 
     * @return
     *     possible object is
     *     {@link StoreCustomPageArrayType }
     *     
     */
    public StoreCustomPageArrayType getCustomPageArray() {
        return customPageArray;
    }

    /**
     * Sets the value of the customPageArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link StoreCustomPageArrayType }
     *     
     */
    public void setCustomPageArray(StoreCustomPageArrayType value) {
        this.customPageArray = value;
    }

}
