//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.27 at 04:06:26 PM PDT 
//


package ebay.apis.eblbasecomponents;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MailOptionsTypeCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MailOptionsTypeCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="DoNotSendEmail"/>
 *     &lt;enumeration value="EmailCopyToSender"/>
 *     &lt;enumeration value="HideSenderEmailAddress"/>
 *     &lt;enumeration value="CustomCode"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MailOptionsTypeCodeType")
@XmlEnum
public enum MailOptionsTypeCodeType {

    @XmlEnumValue("DoNotSendEmail")
    DO_NOT_SEND_EMAIL("DoNotSendEmail"),
    @XmlEnumValue("EmailCopyToSender")
    EMAIL_COPY_TO_SENDER("EmailCopyToSender"),
    @XmlEnumValue("HideSenderEmailAddress")
    HIDE_SENDER_EMAIL_ADDRESS("HideSenderEmailAddress"),
    @XmlEnumValue("CustomCode")
    CUSTOM_CODE("CustomCode");
    private final String value;

    MailOptionsTypeCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MailOptionsTypeCodeType fromValue(String v) {
        for (MailOptionsTypeCodeType c: MailOptionsTypeCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
