//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.27 at 04:06:26 PM PDT 
//


package ebay.apis.eblbasecomponents;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 	      Creates or updates a custom page on a user's eBay Store.
 * 	    
 * 
 * <p>Java class for SetStoreCustomPageRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SetStoreCustomPageRequestType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:ebay:apis:eBLBaseComponents}AbstractRequestType">
 *       &lt;sequence>
 *         &lt;element name="CustomPage" type="{urn:ebay:apis:eBLBaseComponents}StoreCustomPageType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SetStoreCustomPageRequestType", propOrder = {
    "customPage"
})
public class SetStoreCustomPageRequestType
    extends AbstractRequestType
{

    @XmlElement(name = "CustomPage")
    protected StoreCustomPageType customPage;

    /**
     * Gets the value of the customPage property.
     * 
     * @return
     *     possible object is
     *     {@link StoreCustomPageType }
     *     
     */
    public StoreCustomPageType getCustomPage() {
        return customPage;
    }

    /**
     * Sets the value of the customPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link StoreCustomPageType }
     *     
     */
    public void setCustomPage(StoreCustomPageType value) {
        this.customPage = value;
    }

}
