//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.27 at 04:06:26 PM PDT 
//


package ebay.apis.eblbasecomponents;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Store theme.
 * 			
 * 
 * <p>Java class for StoreThemeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StoreThemeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ThemeID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ColorScheme" type="{urn:ebay:apis:eBLBaseComponents}StoreColorSchemeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StoreThemeType", propOrder = {
    "themeID",
    "name",
    "colorScheme"
})
public class StoreThemeType {

    @XmlElement(name = "ThemeID")
    protected Integer themeID;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "ColorScheme")
    protected StoreColorSchemeType colorScheme;

    /**
     * Gets the value of the themeID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getThemeID() {
        return themeID;
    }

    /**
     * Sets the value of the themeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setThemeID(Integer value) {
        this.themeID = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the colorScheme property.
     * 
     * @return
     *     possible object is
     *     {@link StoreColorSchemeType }
     *     
     */
    public StoreColorSchemeType getColorScheme() {
        return colorScheme;
    }

    /**
     * Sets the value of the colorScheme property.
     * 
     * @param value
     *     allowed object is
     *     {@link StoreColorSchemeType }
     *     
     */
    public void setColorScheme(StoreColorSchemeType value) {
        this.colorScheme = value;
    }

}
